source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'ZSWTappableLabel_Example', :exclusive => true do
  pod "ZSWTappableLabel", :path => "../"
  pod 'ZSWTaggedString', '~> 2.0'
  pod 'ZSWTaggedString/Swift', '~> 2.0'
  pod 'SnapKit', '~> 0.18.0'
  pod 'Masonry', '~> 0.6.3'
end

target 'Tests', :exclusive => true do
  pod "ZSWTappableLabel", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
