use_frameworks!

platform :ios, '10.0'

target :ZSWTappableLabel_Example do
  pod "ZSWTappableLabel", :path => "../"
  pod 'ZSWTaggedString', '~> 4.0'
  pod 'ZSWTaggedString/Swift', '~> 4.0'
  pod 'SnapKit'
  pod 'Masonry'

  target 'Tests' do
    inherit! :search_paths
    pod 'Specta'
    pod 'Expecta'
  end
end