source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZSWTappableLabel_Example', :exclusive => true do
  pod "ZSWTappableLabel", :path => "../"
  pod 'ZSWTaggedString', '~> 2.0'
  pod 'ZSWTaggedString/Swift', '~> 2.0'
end

target 'Tests', :exclusive => true do
  pod "ZSWTappableLabel", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
